FASTAI CHAPTER 04 - QUIZ

1) How is a grayscale image represented on a computer? How is a color image?

In [ ]:
# Gray scale image = 1 channel of 2D array of pixels with values from 0 to 255
# Color image = 3 channels of 2D array of pixels with values from 0 to 255, one
# channel for each of the RGB colors
# Though unused here, common color image can include a 4th channel for alpha

2) How are the files and folders in the MNIST_SAMPLE dataset structured? Why?

In [ ]:
# The files and folders of the MNIST_SAMPLE dataset are stored in the following
# folder structure:
#   data/mnist_sample/
#     # with 3 and 7 subfolders in the train and valid folders
#     train/ # training set
#     valid/ # validation set
#     labels.csv # labels for the training and validation sets
#                # where 0 == 3 and 1 == 7

3) Explain how the "pixel similarity" approach to classifying digits works.

In [ ]:
# The "pixel similarity" approach to classifying digits is to :
# 1. Accumulate the pixel values for each digit class
# 2. Divide the accumulated pixel values by the number of images in the class
# 3. The resulting "average digit" will have blurry edges representing uncertainty
# 4. For each image, calculate the DISTANCE between this image and the "average digit"
# 5. Unfortunately this can only distinguish between 3 and not a 3 with respect to 7
# 6. And doesn't scale to compare against the whole 0-9 set of digits
# 7. This approach doesn't allow our model to LEARN from data and improve

4) What is a list comprehension?  Create one now that selects odd numbers from a list and doubles them.

In [24]:
from fastai.vision.all import random

# Standard python list
listnum = []
randomlist = random.sample(range(0, 10), 5)
for num in randomlist:
    print(f'{num}')
    if(num%2 == 1): # if odd
        listnum.append(num * 2) # double it
        print(f'Adding [{num}] to list as [{listnum[-1]}]')

# List comprehension does all that in one line
listcomprehension = [num * 2 for num in randomlist if num%2 ==1]
print(f'{listcomprehension} # List comprehension')

5
Adding [5] to list as [10]
1
Adding [1] to list as [2]
0
3
Adding [3] to list as [6]
4
[10, 2, 6] # List comprehension


5) What is a rank-3 tensor?

In [ ]:
# Rank is the number of axes in a tensor 
# A rank 3 tensor is a 3D array of numbers
# An images has a rank of 3 => (height, width, channels)
# Grey scale images have 1 channel, while color images have 3 channels for RGB
# A common image that handles transparency has 4 channels, RGB + alpha


# Is this autopilot comment correct?
# Rank 0 is a scalar
# Rank 1 is a vector
# Rank 2 is a matrix
# Rank 3 is a 3D tensor
# Rank 4 is a 4D tensor

6) What is the difference between tensor rank and shape? How do you get the rank from the shape?

In [ ]:
# Rank is the number of axes in a tensor
# A stack of MNIST images has a rank of 3 => (height, width, channels)
# A tensor shape is the size of each axis => the mnist_3.shape is 
# torch.Size([6131, 28, 28])

7) What are RMSE and L1 norm?

In [ ]:
# L1 norm is the sum of the absolute values of the elements in a tensor
# Also known as the Manhattan distance

# RMSE is Roof Mean Square Error is frequently used to measure the difference 
# between the predicted and actual values of a model
# Also known as the Euclidean distance or L2 norm

# The lower the value, the better the model is : 0 is perfect in principle

# TODO : What is the difference between L1 and L2 norm?
# Euclidean distance is usually preferred over Manhattan distance when there is
# HIGH DIMENSIONALITY, because the Euclidean distance is more sensitive to
# outliers in high dimensional space
# Manhattan distance is usually preferred over Euclidean distance when there is
# LOW DIMENSIONALITY, because the Manhattan distance is more sensitive to
# outliers in low dimensional space
# What does this mean lol?

# ANSWER : Euclidean distance is the straight line distance between two points
# Manhattan distance is the sum of the absolute differences between two points
# Euclidean distance is the length of "as the crow flies" where as Manhattan
# distance is the length of "as the taxi drives" transformed by roads and 
# traffic lights

8) How can you apply a calculation on thousands of numbers at once, many thousands of times faster than a Python loop?

In [ ]:
# You can apply a calculation on thousands of numbers at once, many thousands of
# times faster than a Python loop by using the native code in the Pytorch library
# as opposed to pure Python math operations

9) Create a 3x3 tensor array containing the numbers 1 to 9.  Double it.  Select the bottom right four numbers.

In [44]:
from fastai.vision.core import tensor
# 3x3 tensor array containing the numbers 1 to 9
tns = tensor([[1,2,3],[4,5,6],[7,8,9]])
print(f'{tns} # 3x3 tensor the numbers 1 to 9')

# double all the number in the tensors
tns = tns * 2
print(f'{tns} # tensor doubled')
print(f'{tns[1:,]} # row 1 and beyond')
print(f'{tns[0:,1:]} # column 1 and beyond')
# select the bottom right 4 numbers
tns = tns[1:, 1:]
print(f'{tns} # bottom right 4 numbers')

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) # 3x3 tensor the numbers 1 to 9
tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]) # tensor doubled
tensor([[ 8, 10, 12],
        [14, 16, 18]]) # row 1 and beyond
tensor([[ 4,  6],
        [10, 12],
        [16, 18]]) # column 1 and beyond
tensor([[10, 12],
        [16, 18]]) # bottom right 4 numbers


10) What is broadcasting?

In [ ]:
# Broadcasting is the ability to perform operations on tensors of different shapes
# by automatically expanding the smaller tensor to match the shape of the larger
# tensor
# For example, you can add a scalar to a tensor, and the scalar will be added to
# each element of the tensor
# Or you can add a vector to a matrix, and the vector will be added to each row of
# the matrix
# Or you can add a matrix to a 3D tensor, and the matrix will be added to each
# slice of the 3D tensor
# Or you can add a 3D tensor to a 4D tensor, and the 3D tensor will be added to
# each element of the 4D tensor
# Broadcasting is a very powerful feature of Pytorch

11) Are metrics generally calculated using the training set or validation set? Why?

In [ ]:
# Metrics are generally calculated using the validation set
# If using the training set, the model will be overfitting to the training set
# and will not generalize well in production

12) What is SGD?

In [ ]:
# SGD is Stochastic Gradient Descent

13) Why does SGD use mini-batches?

In [ ]:
# SGD uses mini-batches because it maps better to the hardware of modern GPUs
# which are optimized for parallel processing
# And as a result will train faster

14) What are the seven steps in SGD for machine learning?

In [ ]:
# The seven steps in SGD for machine learning are:
# 1) Initialize the weights (RANDOMLY for NEW model or add to PREVIOUS model weights for TRANSFER learning)
# 2) Calculate predictions
# 3) Calculate loss i.e. measure distance from prediction to expected result
# 4) Calculate gradient i.e. approximation of direction and magnitude that parameter needs to change
# 5) Step update the weights in the direction of the gradient
# 6) Repeat from (2)
# 7) Stop : either from limited resource or error metric is acceptable

15) How do we initialize the weights in a model?

In [ ]:
# We initialize the weights in a model by:
# 1) Randomly assigning weights to the model when we want to train from scratch
# 2) Else if we are transfer learning, we add to the previous model weights and do nothing
#   to the weights that are already trained, and update from there
# We want to train from scratch when we want to build we need to solve a problem
# specific to our data, many tabular models are trained from scratch
# We want to transfer learn when there's existing knowledge that are already available
# that we can build on top of, many computer vision models are transfer learned
# because shape and color are universal concepts that have WIDE carry-over